version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - client

  client:
    build: ./client
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production

  mock-xero-api:
    image: jaypeng2015/show-me-the-money
    ports:
      - "3000:3000"